name: "Run CI"

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.16.1
          cache: true
      - run: pixi run test
