name: "Run CI"

on: pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        py-version:
          - "3.10"
          - 3.11
          - 3.12
    steps:
      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.16.1
          cache: true
      - run: pixi run test
